export const depositOfferTiles = [
	{
		title: "Lokata mobilna",
		percent: 5.5,
		minimumAmount: 1000,
		maximumAmount: 50000,
		description: "w skali 3 miesięcy",
		monthsNumber: 3,
		bgColor: "#FFB532",
	},
	{
		title: "Lokata terminowa",
		percent: 6,
		minimumAmount: 10000,
		maximumAmount: 75000,
		description: "w skali roku",
		monthsNumber: 12,
		bgColor: "#FFC920",
	},
	{
		title: "Lokata walutowa",
		percent: 2,
		minimumAmount: 500,
		maximumAmount: 3000,
		description: "w skali roku",
		monthsNumber: 12,
		bgColor: "#E4AB3B",
	},
	{
		title: "Lokata sezonowa",
		minimumAmount: 1000,
		maximumAmount: 150000,
		percent: 4.5,
		description: "w skali miesiąca",
		monthsNumber: 1,
		bgColor: "#C49C73",
	},
];
