enum ActionTypes {
	CHANGE_SITE = "CHANGE_SITE",
	CHANGE_ACCOUNT_OFFER_FIELDS = "CHANGE_ACCOUNT_OFFER_FIELDS",
	CHANGE_DEPOSIT_OFFER_FIELDS = "CHANGE_DEPOSIT_OFFER_FIELDS",
}

export const {
	CHANGE_SITE,
	CHANGE_ACCOUNT_OFFER_FIELDS,
	CHANGE_DEPOSIT_OFFER_FIELDS,
} = ActionTypes;
