enum ActionTypes {
	CHANGE_SITE = "CHANGE_SITE",
	CHANGE_ACCOUNT_OFFER_FIELDS = "CHANGE_ACCOUNT_OFFER_FIELDS",
	CHANGE_DEPOSIT_OFFER_FIELDS = "CHANGE_DEPOSIT_OFFER_FIELDS",
	CHANGE_CURRENT_REGISTER_PAGE = "CHANGE_CURRENT_REGISTER_PAGE",
	CHANGE_SELECTED_ACCOUNT_TYPE = "CHANGE_SELECTED_ACCOUNT_TYPE",
}

export const {
	CHANGE_SITE,
	CHANGE_ACCOUNT_OFFER_FIELDS,
	CHANGE_DEPOSIT_OFFER_FIELDS,
	CHANGE_CURRENT_REGISTER_PAGE,
	CHANGE_SELECTED_ACCOUNT_TYPE,
} = ActionTypes;
